### ISSUE TITLE
PCA10056: Part of the HEX regions are out of the device memory size

### ISSUE THREAD

**Issue by lonelycorn** [adafruit/Adafruit_nRF52_Bootloader#277]
### Operating System

Windows 11

### INFO_UF2.TXT

N/A

### What happened ?

I downloaded [pca10056_bootloader-0.7.0_s140_6.1.1.hex](https://github.com/adafruit/Adafruit_nRF52_Bootloader/releases/download/0.7.0/pca10056_bootloader-0.7.0_s140_6.1.1.hex) from the 0.7.0 release, and used Programmer v3.0.3 from [nRF Connect](https://www.nordicsemi.com/Products/Development-tools/nrf-connect-for-desktop) to flash an [nRF52840-DK](https://www.nordicsemi.com/Products/Development-hardware/nrf52840-dk). 

The programmer showed the following warning (see screenshot)
```
Part of the HEX regions are out of the device memory size, but you can still proceed write operation
```

The device seems to be working fine-ish after the flash. At least for a couple of days I was able to flash Arduino sketches using the Arduino IDE via the adafruit package.

### How to reproduce ?

1. download [pca10056_bootloader-0.7.0_s140_6.1.1.hex](https://github.com/adafruit/Adafruit_nRF52_Bootloader/releases/download/0.7.0/pca10056_bootloader-0.7.0_s140_6.1.1.hex) from the 0.7.0 release
2. use Programmer v3.0.3 from [nRF Connect](https://www.nordicsemi.com/Products/Development-tools/nrf-connect-for-desktop) to flash an [nRF52840-DK](https://www.nordicsemi.com/Products/Development-hardware/nrf52840-dk)

### Screenshots

![part-of-hex-regions-are-out-of](https://user-images.githubusercontent.com/4413190/190713473-201f6810-7ee6-4c47-b2b9-7d54e9b4b868.png)

**Comment by hathach** [comment]
did the programmer specify which region is out of the flash. It is probably due to the ucir register for mbr/bootloader at 0x10001014. And it should be safe to program

```
- file: 'feather_nrf52840_express_bootloader-0.7.0-8-gb55f516-dirty_s140_6.1.1.hex'
  entry: 0xF000C4E1
  data:
  - { first: 0x00000000, last: 0x00000AFF, length: 0x00000B00 }
  - { first: 0x00001000, last: 0x00025DE7, length: 0x00024DE8 }
  - { first: 0x000F4000, last: 0x000FD333, length: 0x00009334 }
  - { first: 0x000FD800, last: 0x000FD857, length: 0x00000058 }
  - { first: 0x10001014, last: 0x1000101B, length: 0x00000008 }
```
